server:
  port: 8081

spring:
  datasource:
    url: "jdbc:postgresql://HOST:PORT/DATABASE"
    username: "USERNAME"
    password: "PASSWORD"
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: "true"
    generate-ddl: "true"
    database-platform: org.hibernate.dialect.PostgresPlusDialect
    hibernate:
      ddl-auto: "update"
    properties:
      hibernate:
        format_sql: "true"